/* generated by compiler */
/* CLUSTER CONFIGURATION */
__mpsoc_cluster_max_cpus = 4;
.cluster_channel_width   = 4;
/* NOC CHANNEL CONFIGURATION */
__local_noc_send_channels  = 0;
__local_noc_recv_channels  = 0;
__shared_noc_send_channels = 0;
__shared_noc_recv_channels = 0;
/* MEMORY CONFIGURATION */
__coreva_instr_mem_origin  = 0x0;
__coreva_instr_mem_length  = 0x100000;
__coreva_local_mem_origin  = 0x100000;
__coreva_local_mem_length  = 0x100000;
__coreva_shared_mem_origin = 0x60000000;
__coreva_shared_mem_length = 0x0;
